<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>SurfTimer.Api</RootNamespace>
		<UserSecretsId>d9e4afdd-8c6b-4147-95aa-f512b6ad1282</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
		<!-- Explicit Microsoft.OpenApi added back to ensure compile-time availability of OpenAPI
		models -->
		<PackageReference Include="Microsoft.OpenApi" Version="1.6.23" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"
			Version="1.22.1" />
		<PackageReference Include="MySqlConnector" Version="2.6.1" />
		<PackageReference Include="MySqlConnector.DependencyInjection" Version="2.6.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
		<ProjectReference Include="..\SurfTimer.Shared\SurfTimer.Shared.csproj" />
	</ItemGroup>

</Project>
